# Database
spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://127.0.0.1:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password:
      hikari:
          auto-commit: false
          data-source-properties:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: false
      properties:
          hibernate.id.new_generator_mappings: true
          hibernate.connection.provider_disables_autocommit: true
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: false
          hibernate.multiTenancy: DATABASE
          hibernate.tenant_identifier_resolver: com.example.saas.jpa.tenant.MultiTenantIdentifierResolver
          hibernate.multi_tenant_connection_provider: com.example.saas.jpa.tenant.MultiTenantConnectionProviderImpl
          hibernate.jdbc.time_zone: Asia/Shanghai
          hibernate.jdbc.batch_size: 500
          hibernate.order_inserts: true
          hibernate.order_updates: true
      open-in-view: false
      hibernate:
          ddl-auto: none
          naming:
              physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
              implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  liquibase:
      contexts: dev
      change-log: classpath:liquibase/master.xml
  application:
    name: saas

server:
  port: 6666

